"""empty message

Revision ID: 4e281c6a817d
Revises: 5c8c886f46f7
Create Date: 2022-04-01 08:00:33.761715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e281c6a817d'
down_revision = '5c8c886f46f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('text', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'text')
    # ### end Alembic commands ###
