"""empty message

Revision ID: a0b36953f198
Revises: 4e281c6a817d
Create Date: 2022-04-01 08:02:47.989888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b36953f198'
down_revision = '4e281c6a817d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'text')
    # ### end Alembic commands ###
